import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { container } from "./app.css";
import { AuthProvider } from "@/components/Auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <AuthProvider>
        <body className={container}>{children}</body>
      </AuthProvider>
    </html>
  );
}
